import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LayoutComponent } from './layout/layout.component';
import { HeaderComponent } from './layout/header/header.component';

import {
  ButtonModule,
  CheckboxModule,
  CarouselModule,
  DataTableModule,
  DropdownModule,
  // DialogModule,
  FileUploadModule,
  GrowlModule,
  InputSwitchModule,
  InputTextareaModule,
  InputTextModule,
  InputMaskModule,
  MegaMenuModule,
  MenuModule,
  MultiSelectModule,
  PanelModule,
  PaginatorModule,
  LightboxModule,
  SpinnerModule,
  TieredMenuModule,
  PickListModule,
  TreeModule,
  OverlayPanelModule,
  SharedModule as _SharedModule,
  ConfirmDialogModule,
  ToggleButtonModule,
  RadioButtonModule,
  TooltipModule,
} from 'primeng/primeng';
import { LoadingComponent } from './loading/loading.component';
@NgModule({
  imports: [
    CommonModule,
    ButtonModule,
    CheckboxModule,
    CarouselModule,
    CommonModule,
    DropdownModule,
    DataTableModule,
    FileUploadModule,
    FileUploadModule,
    GrowlModule,
    InputSwitchModule,
    InputTextareaModule,
    InputTextModule,
    InputMaskModule,
    MegaMenuModule,
    MenuModule,
    MultiSelectModule,
    PanelModule,
    PaginatorModule,
    LightboxModule,
    SpinnerModule,
    SpinnerModule,
    TieredMenuModule,
    ToggleButtonModule,
    RadioButtonModule,
    RadioButtonModule,
    PickListModule,
    TreeModule,
    OverlayPanelModule,
    ConfirmDialogModule,
    _SharedModule,
    TooltipModule
  ],
  declarations: [
    LayoutComponent,
    HeaderComponent,
    LoadingComponent,
  ],
  exports: [
    CommonModule,
    ButtonModule,
    CheckboxModule,
    CarouselModule,
    CommonModule,
    DropdownModule,
    DataTableModule,
    FileUploadModule,
    FileUploadModule,
    GrowlModule,
    InputSwitchModule,
    InputTextareaModule,
    InputTextModule,
    InputMaskModule,
    MegaMenuModule,
    MenuModule,
    MultiSelectModule,
    PanelModule,
    PaginatorModule,
    LightboxModule,
    SpinnerModule,
    SpinnerModule,
    TieredMenuModule,
    ToggleButtonModule,
    RadioButtonModule,
    RadioButtonModule,
    PickListModule,
    TreeModule,
    OverlayPanelModule,
    ConfirmDialogModule,
    _SharedModule,
    TooltipModule,
    LoadingComponent,
  ]
})
export class SharedModule { }
