import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LayoutComponent } from './layout/layout.component';
import { HeaderComponent } from './layout/header/header.component';
import { BlockUIModule } from 'primeng/blockui';

import {
  ButtonModule,
  CheckboxModule,
  CarouselModule,
  DataTableModule,
  DropdownModule,
  // DialogModule,
  FileUploadModule,
  GrowlModule,
  InputSwitchModule,
  InputTextareaModule,
  InputTextModule,
  InputMaskModule,
  MegaMenuModule,
  MenuModule,
  MultiSelectModule,
  PanelModule,
  PaginatorModule,
  LightboxModule,
  SpinnerModule,
  TieredMenuModule,
  PickListModule,
  TreeModule,
  OverlayPanelModule,
  SharedModule as _SharedModule,
  ConfirmDialogModule,
  ToggleButtonModule,
  RadioButtonModule,
  TooltipModule,
} from 'primeng/primeng';
import { TableModule } from 'primeng/table';
import { LoadingComponent } from './loading/loading.component';
import { MenuComponent } from './layout/menu/menu.component';
import { SidebarComponent } from './layout/sidebar/sidebar.component';
import { SubmenuComponent } from './layout/submenu/submenu.component';
@NgModule({
  imports: [
    CommonModule,
    ButtonModule,
    CheckboxModule,
    CarouselModule,
    CommonModule,
    DropdownModule,
    DataTableModule,
    FileUploadModule,
    FileUploadModule,
    GrowlModule,
    InputSwitchModule,
    InputTextareaModule,
    InputTextModule,
    InputMaskModule,
    MegaMenuModule,
    MenuModule,
    MultiSelectModule,
    PanelModule,
    PaginatorModule,
    LightboxModule,
    SpinnerModule,
    SpinnerModule,
    TieredMenuModule,
    ToggleButtonModule,
    RadioButtonModule,
    RadioButtonModule,
    PickListModule,
    TreeModule,
    OverlayPanelModule,
    ConfirmDialogModule,
    _SharedModule,
    TooltipModule,
    BlockUIModule,
    TableModule,
  ],
  declarations: [
    LayoutComponent,
    HeaderComponent,
    LoadingComponent,
    MenuComponent,
    SidebarComponent,
    SubmenuComponent,
  ],
  exports: [
    CommonModule,
    ButtonModule,
    CheckboxModule,
    CarouselModule,
    CommonModule,
    DropdownModule,
    DataTableModule,
    FileUploadModule,
    FileUploadModule,
    GrowlModule,
    InputSwitchModule,
    InputTextareaModule,
    InputTextModule,
    InputMaskModule,
    MegaMenuModule,
    MenuModule,
    MultiSelectModule,
    PanelModule,
    PaginatorModule,
    LightboxModule,
    SpinnerModule,
    SpinnerModule,
    TieredMenuModule,
    ToggleButtonModule,
    RadioButtonModule,
    RadioButtonModule,
    PickListModule,
    TreeModule,
    OverlayPanelModule,
    ConfirmDialogModule,
    _SharedModule,
    TooltipModule,
    LoadingComponent,
    BlockUIModule,
    SubmenuComponent,
    TableModule,
  ]
})
export class SharedModule { }
